name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        clean: false
        submodules: 'recursive'
    - run: |
        git fetch --prune --unshallow --tags

    - name: Get dependencies and build
      run: |
        go get github.com/rakyll/statik
        export PATH=$PATH:~/go/bin/
        statik -src=models -f
        sudo apt-get update
        sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
        chmod +x ./build.sh
        ./build.sh -r b

    - name: Upload binary files (linux_arm)
      uses: actions/upload-artifact@v2
      with:
        name: cloudreve_linux_arm
        path: release/cloudreve*linux_arm.*
