name: Ubuntu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSH connection to Actions
      uses: csexton/debugger-action@master
