name: Ubuntu
on:
  workflow_dispatch:

jobs:
  SSH_Build:
    runs-on: ubuntu-16.04
    steps:
     - name: Set up Go 1.13
       uses: actions/setup-go@v1
       with:
         go-version: 1.13
       id: go
     - name: Check out code into the Go module directory
       uses: actions/checkout@v2
       with:
         clean: false
         submodules: 'recursive'
     - run: |
         git fetch --prune --unshallow --tags
     - name: Get dependencies and build
       run: |
         go get github.com/rakyll/statik
         export PATH=$PATH:~/go/bin/
         statik -src=models -f
         sudo apt-get update
         sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross

     - name: Setup Debug Session
       uses: csexton/debugger-action@master
