name: Test
  
on:
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-16.04
    steps:

    - name: Test
      run: wget https://hole.datahub.tk/file/backup.tar.gz

    - name: Upload binary files (linux_arm)
      uses: actions/upload-artifact@v2
      with:
        name: backup_conf
        path: backup.tar.gz
